### ISSUE TITLE
Improve AP actor linking

### ISSUE THREAD

**Issue by slice** [slice/dogbot#13]
* Add explicit detection and support for Pleroma.
* Generalize the code a little.

**Comment by lnmds** [comment]
Here's some things for detecting instance software via Nodeinfo:
 - make a `GET /.well-known/nodeinfo`, follow the link (should be only one, with a `rel` of `"http://nodeinfo.diaspora.software/ns/schema/2.0"`), [more info about the nodeinfo protocol, if wanted](http://nodeinfo.diaspora.software/protocol.html)
 - make the request to the given link, with valid `Accept` header
 - from there, extract `software` field, e.g `{"version":"0.9.0-782-g6383fa3a","name":"Pleroma"}`
 - be happy from there, other known values for `name` i know of are: `pixelfed`, `peertube`, 

**Note**: for mastodon instances, you can try querying the `/api/v1/instance` endpoint if and only if webfinger fails (pleroma's mastoapi [implements that too](https://f.l4.pm/api/v1/instance))

If all fails, maybe just put a generic activitypub logo next instead of the software's logo? [logo is here, in svg](https://activitypub.rocks/static/images/ActivityPub-logo.svg), "ActivityPub logo by mray, released into public domain under CC0 1.0."

[pleroma website contains a logo](https://pleroma.social/), [peertube too](https://joinpeertube.org/img/brand.png), [pixelfed as well](https://pixelfed.social/img/pixelfed-icon-color.svg)

**Comment by slice** [comment]
I'm only going to implement Pleroma support because I'm only interested in federated microblogging protocols.

Adding support for more than one linked AP actor will also require database changes which I do not wish to implement at this time.

**Comment by lnmds** [comment]
There are other AP implementations for "microblogging" you may be interested in, then:
 - [microblog.pub](https://github.com/tsileo/microblog.pub)
 - [kroeg](https://puckipedia.com/kroeg)

And while I do agree on keeping one linked AP actor per user, I'd see it as better if the user can choose their "main" AP account to be shown on their profile card instead of being only Mastodon or Pleroma, the code would still need to use nodeinfo to reliably detect a Pleroma instance too, so...

**Comment by slice** [comment]
I'm only interested in Pleroma and Mastodon at this point.

And users can only ever have one linked account Not sure what you mean by "main" AP when you can only have one.

**Comment by lnmds** [comment]
example: suppose someone has a writefreely account and a pleroma account, and they want to put the writefreely account as the one other people know them for

**Comment by slice** [comment]
Right, but the bot doesn't support this at the moment.

**Comment by slice** [comment]
I am going to eventually phase out support for linking AP actors to user profiles completely because of the exploitability of letting users command the bot to make requests to (pretty much) any domain.
